SELECT A.CODIGO, A.CODIGOBARRA, A.DESCRICAO, A.APLICACAO,SUM(B.QUANTIDADE) AS QTDCOMPRA,
A.PRECOCUSTO, A.PRECOVENDA
FROM CADPRODUTO A
INNER JOIN MOVNOTAITEM B ON
A.EMPRESA = B.EMPRESA AND 
A.CODIGO = B.CODIGOPRODUTO
WHERE B.MOVIMENTACAO = 'S'
AND B.PROCEDIMENTO = 'O'
GROUP BY A.CODIGO, A.DESCRICAO, A.APLICACAO
ORDER BY A.APLICACAO
