SELECT A.CODIGOPRODUTO AS CODIGO, B.DESCRICAO, SUM(A.QUANTIDADE) AS QTD, SUM(A.VALORTOTAL) AS VLRTOT
   FROM MOVNOTAITEM A
   INNER JOIN CADPRODUTO B ON
      B.EMPRESA = A.EMPRESA AND
      B.CODIGO = A.CODIGOPRODUTO
   WHERE A.EMPRESA = '00001' AND
      A.MOVIMENTACAO = 'S' AND
      A.PROCEDIMENTO = 'V' AND
      A.DATAREGISTRO BETWEEN ?[T]DataIni AND ?[T]DataFin  
   GROUP BY A.EMPRESA, A.CODIGOPRODUTO, B.DESCRICAO